# Import / Lib

In [2]:
!pip install drain3

from drain3 import TemplateMiner
from drain3.template_miner_config import TemplateMinerConfig
import pandas as pd
import numpy as np

Collecting drain3
  Downloading drain3-0.9.11.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Collecting jsonpickle==1.5.1 (from drain3)
  Downloading jsonpickle-1.5.1-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting cachetools==4.2.1 (from drain3)
  Downloading cachetools-4.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading cachetools-4.2.1-py3-none-any.whl (12 kB)
Downloading jsonpickle-1.5.1-py2.py3-none-any.whl (37 kB)
Building wheels for collected packages: drain3
  Building wheel for drain3 (setup.py) ... done
  Created wheel for drain3: filename=drain3-0.9.11-py3-none-any.whl size=23998 sha256=058d1012b524f611c56361553cf8f8ae97602f2d73a6bf401a40a45217f480ff
  Stored in directory: /root/.cache/pip/wheels/3f/d1/46/58e1747b3d77c4990f838e1c1f610f5aab1a21889cc9bff5c2
Successfully built drain3
Installing collected packages: jsonpickle, cachetools, drain3
  Attempting uninstall: jsonpickle
    Found existing installation: jsonpickle 4.1.1
    Uninstalling jsonpickle-4.1.1:
      Successfully uninstalled jsonpickle-4.1.1
  Attempting uninstall: cachetools
    Found existing installation: cachetools 6.2.6
    Uninstalling cachetools-6.2.6:
      Successfully uninstalled cachetools-6.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyiceberg 0.11.1 requires cachetools<7.0,>=5.5, but you have cachetools 4.2.1 which is incompatible.
Successfully installed cachetools-4.2.1 drain3-0.9.11 jsonpickle-1.5.1

# Config / Global

In [3]:
LOGFILE = 'BGL.log'

In [4]:
log_lines = list()
with open(LOGFILE, 'r') as f:
    for line in f:
        log_lines.append(line)
print(f"Total: {len(log_lines)} lines")
log_lines[:10]

Total: 1706057 lines

['- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.363779 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.527847 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.675872 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.823719 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.982731 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.131467 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.293532 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.428563 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.601412 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n',
 '- 1117838571 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.51.749199 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n']

In [42]:
def build_miner(sim_th=0.4, drain_depth=4):
  config = TemplateMinerConfig()
  config.drain_sim_th = sim_th
  config.drain_depth = drain_depth

  miner = TemplateMiner(config=config)

  return miner

def parser(log_lines, sim_th=0.4, drain_depth=4):
  miner = build_miner(sim_th, drain_depth)

  log_parsed = []
  templates = []

  for line in log_lines:
    result = miner.add_log_message(line)
    data = {
        'template_id': result['cluster_id'],
        'template': result['template_mined'],
        'log': line,
        'timestamp': int(line.split(' ')[1]),
        'truth_label': 1 if line.split(' ')[0] == '-' else -1
    }
    log_parsed.append(data)


  for cluster in miner.drain.clusters:
    data = {
        'id': cluster.cluster_id,
        'count': cluster.size,
        'template': cluster.get_template()
    }
    templates.append(data)

  return log_parsed, templates, miner

# Tuning SIMTH

In [11]:
thresholds = [0.1, 0.2, 0.3, 0.4, 0.5]

for th in thresholds:
  log_parsed, templates, miner = parser(log_lines, sim_th=th)

  print(f"Chỉ số Threshold = {th}: {len(templates)} templates")

Chỉ số Threshold = 0.1: 67 templates
Chỉ số Threshold = 0.2: 95 templates
Chỉ số Threshold = 0.3: 157 templates
Chỉ số Threshold = 0.4: 253 templates
Chỉ số Threshold = 0.5: 545 templates

In [43]:
log_parsed, templates, miner = parser(log_lines, sim_th=0.3) # Số lượng template ở mức trung bình, không quá lớn. Tốc độ build miner cũng vùa phải không quá lâu
print(f"Tổng số template: {len(templates)}")
for template in templates:
  print(template)

Tổng số template: 157
{'id': 1, 'count': 64933, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO instruction cache parity error corrected'}
{'id': 2, 'count': 388, 'template': '- <*> <*> <*> <*> <*> RAS LINKCARD INFO MidplaneSwitchController performing bit sparing on <*> bit <*>'}
{'id': 3, 'count': 767777, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> <*>'}
{'id': 4, 'count': 4413, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> ddr errors(s) detected and corrected on rank 0, symbol <*> bit <*>'}
{'id': 5, 'count': 1481, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> <*> <*> error(s) (dcr <*> detected and corrected'}
{'id': 6, 'count': 651, 'template': '- <*> 2005.06.03 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 7, 'count': 4, 'template': '- <*> <*> R16-M1-N2-C:J17-U01 <*> R16-M1-N2-C:J17-U01 RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*> <*>'}
{'id': 8, 'count': 3408, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO total of <*> ddr error(s) detected and corrected'}
{'id': 9, 'count': 4736, 'template': '- <*> <*> <*> <*> <*> RAS APP FATAL ciod: Error loading <*> invalid or missing program image, No such file or directory'}
{'id': 10, 'count': 4738, 'template': '- <*> 2005.06.03 <*> <*> <*> RAS <*> INFO <*> <*> <*> <*>'}
{'id': 11, 'count': 1521, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> tree receiver <*> in re-synch state event(s) (dcr <*> detected'}
{'id': 12, 'count': 15, 'template': '- <*> <*> NULL <*> NULL RAS MMCS INFO <*> has been started: <*> <*> <*> <*> <*> <*> <*> <*> <*>'}
{'id': 13, 'count': 2210, 'template': '- <*> <*> <*> <*> <*> RAS APP FATAL ciod: LOGIN <*> failed: No such file or directory'}
{'id': 14, 'count': 5983, 'template': 'APPREAD <*> <*> <*> <*> <*> RAS APP FATAL ciod: failed to read message prefix on control stream (CioStream socket to <*>'}
{'id': 15, 'count': 398, 'template': '- <*> 2005.06.04 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 16, 'count': 152659, 'template': 'KERNDTLB <*> <*> <*> <*> <*> RAS KERNEL FATAL data TLB error interrupt'}
{'id': 17, 'count': 153605, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL FATAL <*> <*> <*>'}
{'id': 18, 'count': 228, 'template': '- <*> 2005.06.05 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 19, 'count': 19, 'template': 'KERNMC <*> <*> <*> <*> <*> RAS KERNEL FATAL machine check interrupt'}
{'id': 20, 'count': 183, 'template': '- <*> 2005.06.05 <*> <*> <*> RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 21, 'count': 176, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL FATAL <*>'}
{'id': 22, 'count': 108402, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL FATAL <*> <*> <*> <*>'}
{'id': 23, 'count': 12375, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL FATAL <*> <*>'}
{'id': 24, 'count': 12531, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL <*> floating pt ex mode <*> <*>'}
{'id': 25, 'count': 2588, 'template': 'KERNRTSP <*> <*> <*> <*> <*> RAS KERNEL FATAL rts panic! - stopping execution'}
{'id': 26, 'count': 4354, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> torus receiver <*> input pipe error(s) (dcr <*> detected and corrected'}
{'id': 27, 'count': 38, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ddr: excessive soft failures, consider replacing the card'}
{'id': 28, 'count': 1213, 'template': '- <*> 2005.06.06 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 29, 'count': 2278, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ciod: Message code <*> is not <*> or 4294967295'}
{'id': 30, 'count': 143, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ciod: pollControlDescriptors: Detected the debugger died.'}
{'id': 31, 'count': 395, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ciod: for node <*> read continuation request but ioState is 0'}
{'id': 32, 'count': 2569, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ciod: cpu 0 at treeaddr <*> sent unrecognized message 0xffffffff'}
{'id': 33, 'count': 1104, 'template': '- <*> 2005.06.07 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 34, 'count': 3, 'template': 'KERNMC <*> <*> <*> <*> <*> RAS KERNEL FATAL machine check interrupt (bit=0x1d): L2 dcache unit data parity error'}
{'id': 35, 'count': 3, 'template': '- <*> 2005.06.07 R17-M0-N1-C:J03-U01 <*> R17-M0-N1-C:J03-U01 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 36, 'count': 432, 'template': '- <*> <*> <*> <*> <*> RAS APP FATAL ciod: LOGIN <*> failed: Permission denied'}
{'id': 37, 'count': 1113, 'template': '- <*> 2005.06.08 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 38, 'count': 11, 'template': 'KERNMC <*> <*> <*> <*> <*> RAS KERNEL FATAL machine check interrupt <*> <*> <*> <*> <*>'}
{'id': 39, 'count': 18, 'template': '- <*> 2005.06.08 R33-M1-ND-C:J15-U11 <*> R33-M1-ND-C:J15-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 40, 'count': 8, 'template': '- <*> 2005.06.08 R33-M1-ND-C:J15-U11 <*> R33-M1-ND-C:J15-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*> <*>'}
{'id': 41, 'count': 17, 'template': '- <*> 2005.06.08 R33-M1-ND-C:J15-U11 <*> R33-M1-ND-C:J15-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*>'}
{'id': 42, 'count': 3, 'template': "- <*> <*> <*> <*> <*> RAS KERNEL FATAL disable flagging of DDR UE's as major internal error.0"}
{'id': 43, 'count': 6, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL FATAL number of correctable errors detected in L3 <*>'}
{'id': 44, 'count': 3, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL FATAL number of lines with parity errors written to L3 EDRAMs...0'}
{'id': 45, 'count': 3, 'template': 'KERNMC <*> <*> <*> <*> <*> RAS KERNEL FATAL DDR machine check register: 0x00000000 0x00010000'}
{'id': 46, 'count': 5, 'template': '- <*> <*> <*> <*> <*> NULL HARDWARE WARNING PrepareForService is being done on this <*> <*> <*> <*> mType(4)) by root'}
{'id': 47, 'count': 978, 'template': '- <*> <*> <*> <*> <*> NULL HARDWARE WARNING <*> <*> <*> <*> <*> <*> <*> <*> as part of Service Action <*>'}
{'id': 48, 'count': 55, 'template': '- <*> <*> UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL HARDWARE <*> <*> <*> <*> <*> <*> <*> <*>'}
{'id': 49, 'count': 3143, 'template': '- <*> <*> <*> <*> <*> NULL DISCOVERY WARNING Node card is not fully functional'}
{'id': 50, 'count': 3133, 'template': '- <*> <*> <*> <*> <*> NULL DISCOVERY SEVERE Can not get assembly information for node card'}
{'id': 51, 'count': 3016, 'template': '- <*> <*> <*> <*> <*> NULL DISCOVERY ERROR Node card status: no ALERTs are active. Clock Mode is Low. Clock Select is Midplane. Phy JTAG Reset is asserted. ASIC JTAG Reset is asserted. Temperature Mask is not active. No temperature error. Temperature Limit Error Latch is clear. PGOOD IS NOT ASSERTED. PGOOD ERROR LATCH IS ACTIVE. MPGOOD IS NOT OK. MPGOOD ERROR LATCH IS ACTIVE. The 2.5 volt rail is OK. The 1.5 volt rail is OK.'}
{'id': 52, 'count': 1352, 'template': '- <*> <*> <*> <*> <*> NULL DISCOVERY WARNING Node card VPD check: <*> node in processor card slot <*> do not match. VPD ecid <*> found <*>'}
{'id': 53, 'count': 1, 'template': '- 1118252717 2005.06.08 R23-M0-NC-I:J18-U11 2005-06-08-10.45.17.699993 R23-M0-NC-I:J18-U11 RAS KERNEL INFO ciod: sendMsgToDebugger: error sending PROGRAM_EXITED message to debugger.'}
{'id': 54, 'count': 2176, 'template': '- <*> 2005.06.09 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 55, 'count': 6, 'template': '- <*> 2005.06.09 <*> <*> <*> RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 56, 'count': 117, 'template': '- <*> 2005.06.10 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 57, 'count': 3, 'template': '- <*> 2005.06.10 R10-M0-N1-C:J14-U11 <*> R10-M0-N1-C:J14-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 58, 'count': 365, 'template': '- <*> 2005.06.11 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 59, 'count': 70, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> torus <*> <*> <*> error(s) (dcr <*> detected and corrected'}
{'id': 60, 'count': 6, 'template': '- <*> <*> NULL <*> NULL RAS MMCS INFO ciodb has been restarted.'}
{'id': 61, 'count': 430, 'template': '- <*> 2005.06.12 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 62, 'count': 1, 'template': '- 1118626381 2005.06.12 R21-M1-N4-I:J18-U11 2005-06-12-18.33.01.485726 R21-M1-N4-I:J18-U11 RAS KERNEL INFO L3 correctable errors exceeds threshold (iar 0xf003da3c lr 0xf003de50)'}
{'id': 63, 'count': 318, 'template': '- <*> 2005.06.13 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 64, 'count': 6, 'template': '- <*> 2005.06.13 <*> <*> <*> RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 65, 'count': 14, 'template': '- <*> <*> UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL CMCS INFO Starting SystemController'}
{'id': 66, 'count': 13, 'template': '- <*> <*> UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL CMCS INFO Controlling BG/L rows [ 0 1 2 3 ]'}
{'id': 67, 'count': 15, 'template': '- <*> <*> UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL <*> <*> <*> <*> <*> <*>'}
{'id': 68, 'count': 63488, 'template': 'KERNSTOR <*> <*> <*> <*> <*> RAS KERNEL FATAL data storage interrupt'}
{'id': 69, 'count': 714, 'template': '- <*> 2005.06.14 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 70, 'count': 18432, 'template': '- <*> 2005.06.14 <*> <*> <*> RAS KERNEL FATAL <*> <*> <*> <*> <*> <*>'}
{'id': 71, 'count': 10243, 'template': '- <*> 2005.06.14 <*> <*> <*> RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 72, 'count': 1730, 'template': '- <*> 2005.06.15 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*> <*>'}
{'id': 73, 'count': 645, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL FATAL external input interrupt (unit=0x02 <*> torus sender <*> retransmission error was corrected'}
{'id': 74, 'count': 28572, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO CE sym <*> at <*> mask <*>'}
{'id': 75, 'count': 1, 'template': '- 1118928543 2005.06.16 R14-M1-ND-C:J16-U11 2005-06-16-06.29.03.194232 R14-M1-ND-C:J16-U11 RAS KERNEL INFO external input interrupt (unit=0x01 bit=0x09): number of corrected SRAM errors has exceeded threshold'}
{'id': 76, 'count': 56, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO suppressing further interrupts of same type'}
{'id': 77, 'count': 18, 'template': '- <*> 2005.06.16 R11-M1-NB-C:J02-U11 <*> R11-M1-NB-C:J02-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 78, 'count': 8, 'template': '- <*> 2005.06.16 R11-M1-NB-C:J02-U11 <*> R11-M1-NB-C:J02-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*> <*>'}
{'id': 79, 'count': 17, 'template': '- <*> 2005.06.16 R11-M1-NB-C:J02-U11 <*> R11-M1-NB-C:J02-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*>'}
{'id': 80, 'count': 809, 'template': '- <*> <*> UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL DISCOVERY INFO Ido chip status changed: <*> <*> <*> <*> status=M <*> <*> <*> <*> PDT 2005'}
{'id': 81, 'count': 129, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ddr: activating redundant bit steering: rank=0 <*>'}
{'id': 82, 'count': 3, 'template': '- <*> 2005.06.17 R03-M1-N7-C:J03-U11 <*> R03-M1-N7-C:J03-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 83, 'count': 3, 'template': '- <*> 2005.06.18 R33-M0-N9-C:J09-U11 <*> R33-M0-N9-C:J09-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 84, 'count': 3, 'template': '- <*> 2005.06.19 R20-M1-N3-C:J14-U01 <*> R20-M1-N3-C:J14-U01 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 85, 'count': 7, 'template': '- <*> 2005.06.20 <*> <*> <*> RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 86, 'count': 3, 'template': '- <*> <*> NULL <*> NULL RAS BGLMASTER INFO BGLMaster has been started: ./BGLMaster --consoleip 127.0.0.1 --consoleport 32035 --configfile bglmaster.init'}
{'id': 87, 'count': 7, 'template': '- <*> <*> UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL DISCOVERY SEVERE <*> <*> <*> <*> <*> with <*> <*> <*> <*> <*>'}
{'id': 88, 'count': 12, 'template': '- <*> 2005.06.20 UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL DISCOVERY SEVERE <*> <*> Status(A)'}
{'id': 89, 'count': 40, 'template': '- <*> <*> UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL DISCOVERY SEVERE While initializing node card iDo machine with LP of <*> caught java.io.IOException: Could not contact iDo with <*> and <*> because java.lang.RuntimeException: Communication error: (DirectIDo for Uninitialized DirectIDo for <*> is in state = COMMUNICATION_ERROR, sequenceNumberIsOk = false, ExpectedSequenceNumber = 0, Reply Sequence Number = -1, timedOut = true, retries = 200, timeout = 1000, Expected Op Command = 5, Actual Op Reply = -1, Expected Sync Command = 10, Actual Sync Reply = -1)'}
{'id': 90, 'count': 1, 'template': '- 1119281895 2005.06.20 UNKNOWN_LOCATION 2005-06-20-08.38.15.500284 UNKNOWN_LOCATION NULL DISCOVERY SEVERE While initializing node card, ido with LP of FF:F2:9F:16:E8:42:00:0D:60:E9:17:BD caught java.lang.IllegalStateException: IDo is not in functional state -- currently in state COMMUNICATION_ERROR'}
{'id': 91, 'count': 3, 'template': '- <*> 2005.06.20 R01-M0-NA-C:J09-U11 <*> R01-M0-NA-C:J09-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*>'}
{'id': 92, 'count': 256, 'template': '- <*> 2005.06.20 <*> <*> <*> RAS KERNEL INFO ciod: Unexpected eof at line 8193 of node map file /p/gb2/cabot/miranda/newmaps/8k_128x64x1_8x4x4.map'}
{'id': 93, 'count': 256, 'template': 'APPCHILD <*> 2005.06.20 <*> <*> <*> RAS APP FATAL ciod: Error creating node map from file /p/gb2/cabot/miranda/newmaps/8k_128x64x1_8x4x4.map: No child processes'}
{'id': 94, 'count': 21, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ddr: Unable to steer rank=0, <*> - rank is already steering symbol <*> Due to multiple symbols being over the correctable e'}
{'id': 95, 'count': 44, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> threshold, consider replacing the card'}
{'id': 96, 'count': 24, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ddr: Unable to steer rank=0, <*> - rank is already steering symbol <*> Due to multiple symbols being over the <*>'}
{'id': 97, 'count': 18, 'template': '- <*> 2005.06.21 R36-M1-NE-C:J11-U11 <*> R36-M1-NE-C:J11-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 98, 'count': 8, 'template': '- <*> 2005.06.21 R36-M1-NE-C:J11-U11 <*> R36-M1-NE-C:J11-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*> <*>'}
{'id': 99, 'count': 17, 'template': '- <*> 2005.06.21 R36-M1-NE-C:J11-U11 <*> R36-M1-NE-C:J11-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*>'}
{'id': 100, 'count': 21, 'template': '- <*> <*> <*> <*> <*> NULL HARDWARE WARNING PrepareForService is being done on this part <*> <*> <*> <*> mType(4)) by root'}
{'id': 101, 'count': 1544, 'template': '- <*> <*> <*> <*> <*> RAS APP FATAL ciod: Error <*> <*> <*> <*> <*> <*> <*> <*> <*>'}
{'id': 102, 'count': 55, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO critical input interrupt (unit=0x0b <*> warning for <*> <*> wire'}
{'id': 103, 'count': 30, 'template': '- <*> <*> - <*> RAS KERNEL FATAL Kill job <*> timed out. Block freed.'}
{'id': 104, 'count': 13156, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> <*> <*>'}
{'id': 105, 'count': 213337, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*>'}
{'id': 106, 'count': 10, 'template': '- <*> 2005.06.22 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*>'}
{'id': 107, 'count': 3, 'template': '- <*> 2005.06.22 R02-M1-N0-C:J12-U11 <*> R02-M1-N0-C:J12-U11 RAS KERNEL INFO <*> <*> <*> <*> <*> <*>'}
{'id': 108, 'count': 1176, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO ciod: <*> <*> <*> <*> <*> <*> <*> at line <*> of node map file <*>'}
{'id': 109, 'count': 144, 'template': 'APPALLOC <*> <*> <*> <*> <*> RAS APP FATAL ciod: Error creating node map from file <*> Cannot allocate memory'}
{'id': 110, 'count': 3, 'template': '- <*> 2005.06.23 R05-M1-N2-C:J06-U11 <*> R05-M1-N2-C:J06-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 111, 'count': 3, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL INFO <*> floating point alignment exceptions'}
{'id': 112, 'count': 9262, 'template': '- <*> 2005.06.26 <*> <*> <*> RAS KERNEL INFO <*> <*> <*> <*> <*> <*>'}
{'id': 113, 'count': 1941, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL <*> program interrupt: fp cr update.............0'}
{'id': 114, 'count': 13, 'template': '- <*> <*> <*> <*> <*> RAS KERNEL FATAL machine check status register: <*>'}
{'id': 115, 'count': 9, 'template': '- <*> <*> UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL DISCOVERY SEVERE Problem communicating with node card, iDo machine with LP of <*> caught java.lang.IllegalStateException: while executing <*> Operation caught java.lang.RuntimeException: Communication error: (DirectIDo for com.ibm.ido.DirectIDo object <*> with image version 13 and card type 4] is in state = COMMUNICATION_ERROR, sequenceNumberIsOk = false, ExpectedSequenceNumber = <*> Reply Sequence Number = -1, timedOut = true, retries = 200, timeout = 1000, Expected Op Command = 2, Actual Op Reply = -1, Expected Sync Command = <*> Actual Sync Reply = -1)'}
{'id': 116, 'count': 4, 'template': '- <*> <*> <*> <*> <*> NULL DISCOVERY SEVERE <*> <*> <*> <*> <*> <*> <*> <*> <*> <*> java.lang.IllegalStateException: while executing <*> Operation caught java.lang.RuntimeException: Communication error: (DirectIDo for com.ibm.ido.DirectIDo object <*> with image version <*> and card type <*> is in state = COMMUNICATION_ERROR, sequenceNumberIsOk = false, ExpectedSequenceNumber = <*> Reply Sequence Number = <*> timedOut = true, retries = 200, timeout = 1000, Expected Op Command = 2, Actual Op Reply = <*> Expected Sync Command = <*> Actual Sync Reply = <*>'}
{'id': 117, 'count': 116, 'template': '- <*> 2005.06.28 R02-M1-N0 <*> R02-M1-N0 NULL DISCOVERY ERROR Node card status: no ALERTs are active. Clock Mode is Low. Clock Select is Midplane. Phy JTAG Reset is asserted. ASIC JTAG Reset is asserted. Temperature Mask is not active. No temperature error. Temperature Limit Error Latch is clear. PGOOD IS NOT ASSERTED. PGOOD ERROR LATCH IS ACTIVE. MPGOOD IS NOT OK. MPGOOD ERROR LATCH IS ACTIVE. THE 2.5 VOLT RAIL IS NOT OK. THE 1.5 VOLT RAIL IS NOT OK.'}
{'id': 118, 'count': 5, 'template': '- 1119972857 2005.06.28 UNKNOWN_LOCATION <*> UNKNOWN_LOCATION NULL HARDWARE SEVERE NodeCard temperature sensor chip <*> is not accessible'}
{'id': 119, 'count': 1, 'template': '- 1119972857 2005.06.28 UNKNOWN_LOCATION 2005-06-28-08.34.17.282522 UNKNOWN_LOCATION NULL HARDWARE SEVERE NodeCard VPD chip is not accessible'}
{'id': 120, 'count': 1, 'template': '- 1119972857 2005.06.28 UNKNOWN_LOCATION 2005-06-28-08.34.17.313955 UNKNOWN_LOCATION NULL DISCOVERY ERROR Node card status: ALERT 0, ALERT 1, ALERT 2, ALERT 3 is (are) active. Clock Mode is Low. Clock Select is Midplane. Phy JTAG Reset is asserted. ASIC JTAG Reset is not asserted. TEMPERATURE MASK IS ACTIVE. No temperature error. Temperature Limit Error Latch is clear. PGOOD is asserted. PGOOD error latch is clear. MPGOOD is OK. MPGOOD error latch is clear. The 2.5 volt rail is OK. The 1.5 volt rail is OK.'}
{'id': 121, 'count': 7, 'template': '- <*> 2005.06.28 <*> <*> <*> RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 122, 'count': 6, 'template': 'KERNSOCK 1119975388 2005.06.28 <*> <*> <*> RAS KERNEL FATAL MailboxMonitor::serviceMailboxes() lib_ido_error: -1019 socket closed'}
{'id': 123, 'count': 1, 'template': 'MASNORM 1119992001 2005.06.28 NULL 2005-06-28-13.53.21.974236 NULL RAS BGLMASTER FAILURE mmcs_server exited normally with exit code 13'}
{'id': 124, 'count': 24, 'template': 'LINKDISC <*> <*> R07-M1-L1-U19-E <*> R07-M1-L1-U19-E RAS LINKCARD FATAL MidplaneSwitchController::sendTrain() port disconnected: R07-M1-L1-U19-E'}
{'id': 125, 'count': 8, 'template': '- <*> 2005.06.29 R02-M0-N9-C:J12-U11 <*> R02-M0-N9-C:J12-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*>'}
{'id': 126, 'count': 3, 'template': '- <*> 2005.06.29 R02-M0-N9-C:J12-U11 <*> R02-M0-N9-C:J12-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*> <*>'}
{'id': 127, 'count': 2, 'template': '- <*> 2005.06.29 R02-M0-N9-C:J12-U11 <*> R02-M0-N9-C:J12-U11 RAS KERNEL FATAL <*> <*> <*> <*> <*> <*>'}

In [29]:
top_templates = sorted(templates, key=lambda x: x['count'], reverse=True)[:10]
pd.DataFrame(top_templates).to_csv('top_templates.csv', index=False)

In [33]:
def build_time_series(log_parsed):
  df = pd.DataFrame(log_parsed)
  time_series_df = df.groupby(['timestamp', 'template_id']).size().unstack(fill_value=0)
  df_flat = time_series_df.reset_index()
  df_flat.columns.name = None
  df_flat = df_flat.rename(columns={'timestamp': 'timestamp'})
  return df_flat

time_series = build_time_series(log_parsed)
time_series = time_series.set_index('timestamp')
time_series

,1,2,3,4,5,6,7,8,9,10,...,148,149,150,151,152,153,154,155,156,157
timestamp,,,,,,,,,,,,,,,,,,,,,
1117838570,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1117838571,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1117838572,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1117838573,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1117838574,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120934811,0,0,33,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1120934812,0,0,33,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1120934813,0,0,33,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1120934814,0,0,31,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1120934815,0,0,13,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [32]:
true_label_df = pd.DataFrame(log_parsed).groupby('timestamp')['truth_label'].min().reset_index().rename(columns={'truth_label': 'label'})
true_label_df

        timestamp  label
0      1117838570      1
1      1117838571      1
2      1117838572      1
3      1117838573      1
4      1117838574      1
...           ...    ...
86852  1120934811      1
86853  1120934812      1
86854  1120934813      1
86855  1120934814      1
86856  1120934815      1

[86857 rows x 2 columns]

In [34]:
true_label_df[true_label_df['label'] == -1]

        timestamp  label
1859   1117869872     -1
1860   1117869873     -1
1861   1117869874     -1
1862   1117869875     -1
1863   1117869876     -1
...           ...    ...
83218  1120912249     -1
83219  1120912250     -1
83220  1120912251     -1
83231  1120913153     -1
83232  1120913154     -1

[25650 rows x 2 columns]

# Isolation Forest + Tuning Contamination

In [35]:
from sklearn.ensemble import IsolationForest
from sklearn.metrics import precision_score, recall_score, f1_score

def build_if(series, contamination=0.3):
  X = series.values
  model = IsolationForest(contamination=contamination, n_estimators=100, random_state=42, n_jobs=-1)
  model.fit(X)

  return model

def calc_metrics_sklearn(true_labels: list, pred_labels: list):
    # pos_label=-1 chỉ định tính toán tập trung vào nhãn -1
    precision = precision_score(true_labels, pred_labels, pos_label=-1, zero_division=0)
    recall = recall_score(true_labels, pred_labels, pos_label=-1, zero_division=0)
    f1 = f1_score(true_labels, pred_labels, pos_label=-1, zero_division=0)

    return {
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1
    }

contaminations = [0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45]

for contamination in contaminations:
  model = build_if(time_series, contamination=contamination)
  pred_labels = model.predict(time_series)
  true_labels = true_label_df['label'].values
  metrics = calc_metrics_sklearn(true_labels, pred_labels)
  print(f"Contamination = {contamination}: {metrics}")

Contamination = 0.1: {'Precision': 0.17049027599860253, 'Recall': 0.05707602339181286, 'F1-Score': 0.0855215118147034}
Contamination = 0.15: {'Precision': 0.21111810033024062, 'Recall': 0.10467836257309941, 'F1-Score': 0.1399603836530442}
Contamination = 0.2: {'Precision': 0.19546873193850423, 'Recall': 0.13185185185185186, 'F1-Score': 0.15747811510523374}
Contamination = 0.25: {'Precision': 0.17086662569145666, 'Recall': 0.14089668615984405, 'F1-Score': 0.15444114441999102}
Contamination = 0.3: {'Precision': 0.1648474133292336, 'Recall': 0.16721247563352826, 'F1-Score': 0.16602152202523807}
Contamination = 0.35: {'Precision': 0.1489767426022406, 'Recall': 0.1705653021442495, 'F1-Score': 0.15904175073159205}
Contamination = 0.4: {'Precision': 0.1489767426022406, 'Recall': 0.1705653021442495, 'F1-Score': 0.15904175073159205}
Contamination = 0.45: {'Precision': 0.1249250449730162, 'Recall': 0.1705653021442495, 'F1-Score': 0.14422046776878575}

# Embedding

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import DBSCAN

# TF-IDF
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([template['template'] for template in templates])
sim_matrix = cosine_similarity(tfidf_matrix)

# Nhóm cluster
distance_matrix = np.clip(1 - sim_matrix, 0, 1)

for esp in np.arange(0.0, 0.5 + 0.01, 0.05):
  if esp == 0.0:
    continue
  dbscan = DBSCAN(eps=esp, min_samples=2, metric='precomputed')
  cluster_labels = dbscan.fit_predict(distance_matrix)

  for template, label in zip(templates, cluster_labels):
      template['cluster_id'] = label

  print(f"cluster label cho esp {esp}: {cluster_labels}")

cluster label cho esp 0.05: [-1 -1  0 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  2 -1  3 -1  2  2  2 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  3  4  4  4 -1 -1 -1 -1 -1 -1 -1
 -1 -1  5 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  6  6 -1
 -1 -1 -1 -1  7  7  7 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  8 -1  8
  9  9  9 -1 -1 -1 -1  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  5 -1 -1 -1
 -1 -1 -1 -1 10 10 10 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 11 11 -1 11 11 -1 -1 -1  2 -1 -1 -1 -1]
cluster label cho esp 0.1: [-1 -1  0 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  2 -1  3 -1  2  2  2 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  3  4  4  4 -1 -1 -1 -1  5 -1 -1
 -1 -1  6 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  7  7 -1
 -1 -1 -1 -1  8  8  8 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  9 -1  9
 10 10 10  5 -1 -1 -1  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 11 11  6 -1 -1 -1
 -1 -1 -1 -1 12 12 12  6 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 13 13 -1 13 13 -1 -1 -1  2 -1 -1 -1 -1]
cluster label cho esp 0.15000000000000002: [-1 -1  0 -1  1  2 -1 -1 -1  2 -1 -1 -1 -1 -1 -1  3  4  5  4  3  3  3 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  5  6  6  6 -1 -1 -1 -1  7 -1  8
 -1 -1  9 -1 -1 10 10 -1 -1 -1  1 -1 -1 -1 11 11 -1 -1  8 -1 12 12 12 -1
 -1 -1 -1 -1 13 13 13 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 14 -1 14
 15 15 15  7 -1 -1 -1  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 16 16  9 -1 -1  9
 -1 -1 -1 -1 17 17 17  9 -1 -1 -1 -1 -1 -1 -1 -1 -1 18 -1 -1 -1 -1 -1 -1
 19 19 -1 19 19 -1 18 -1  3 -1 -1 -1 -1]
cluster label cho esp 0.2: [-1 -1  0 -1  1  2 -1 -1 -1  2 -1 -1 -1 -1 -1 -1  3  4  5  4  3  3  3 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  5  6  6  6 -1 -1 -1 -1  7 -1  8
 -1 -1  9 -1 -1 10 10 -1 -1 -1  1 -1 -1 -1 11 11 -1 -1  8 -1 12 12 12 -1
 -1 -1 -1 -1 13 13 13 -1 -1 -1 -1 -1 -1 -1 -1 -1 14 -1 -1 -1 -1 15 -1 15
 16 16 16  7 -1 -1 -1  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 14 14  9 -1 -1  9
 -1 -1 -1 -1 17 17 17  9 -1 -1 -1 -1 -1 -1 -1 -1 -1 18 -1 -1 -1 -1 -1 -1
 19 19 -1 19 19 -1 18 -1  3 -1 -1 -1 -1]
cluster label cho esp 0.25: [-1 -1  0 -1  1  2 -1 -1 -1  2 -1 -1 -1 -1 -1 -1  3  4  5  4  3  3  3 -1
 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  5  6  6  6 -1 -1 -1 -1  7 -1  8
 -1 -1  9 -1 -1 10 10 -1 -1 -1  1 -1 -1 -1 11 11 -1 -1  8 -1 12 12 12 -1
 -1 -1 -1 -1 13 13 13 -1 -1 -1 -1 -1 -1 -1 -1 -1 14 -1 -1 -1 -1 15 -1 15
 16 16 16  7 -1 -1 -1  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 14 14  9 -1 -1  9
 -1 -1 -1 -1 17 17 17  9 -1 -1 -1  7  7 -1 -1 -1 -1 18 -1 -1 -1 -1 -1 19
 19 19 -1 19 19 -1 18 -1  3 -1 -1 -1 -1]
cluster label cho esp 0.30000000000000004: [-1 -1  0 -1  1  2 -1 -1 -1  2 -1  3 -1 -1 -1 -1  4  5  6  5  4  4  4 -1
 -1  1 -1  7 -1 -1 -1 -1  7 -1 -1 -1 -1  6  8  8  8 -1 -1 -1 -1  9 -1 10
 -1 -1 11 -1 -1 12 12 -1 -1 -1  1  3 -1 -1 13 13 -1 -1 10 -1 14 14 14 -1
 -1 -1 -1 -1 15 15 15 -1 -1 -1 -1 -1 -1 -1 10 10 16 -1 -1 -1 -1 17 -1 17
 18 18 18  9 -1 -1 -1  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 16 16 11 19 19 11
 -1 -1 -1 -1 20 20 20 11 -1 -1 -1  9  9 -1 -1 -1 -1 21 -1 -1 -1 -1 -1 22
 22 22 -1 22 22 -1 21 -1  4 -1 -1 -1 -1]
cluster label cho esp 0.35000000000000003: [-1 -1  0 -1  1  2 -1 -1 -1  2 -1  3 -1 -1 -1 -1  4  5  6  5  4  4  4 -1
 -1  1 -1  7 -1 -1 -1 -1  7 -1 -1 -1  7  6  8  8  8 -1 -1 -1 -1  9 -1 10
 11 -1 12 -1 -1 13 13 -1 -1 -1  1  3 -1 -1 14 14 -1 -1 10 -1 15 15 15 -1
 -1 -1 -1 -1 16 16 16 -1 -1 -1 -1 -1 -1 -1 10 10 17 -1 -1 -1 -1 18 -1 18
 19 19 19  9 -1 -1 -1  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 17 17 12 20 20 12
 -1 -1 -1 -1 21 21 21 12 -1 -1 -1  9  9 -1 11 -1 -1 22 -1 -1 -1 -1 -1 23
 23 23 -1 23 23 -1 22 -1  4 -1 -1 -1 -1]
cluster label cho esp 0.4: [-1 -1  0 -1  1  2 -1  1  3  2 -1  4  3 -1 -1 -1  5  6  7  6  5  5  5 -1
 -1  1 -1  6 -1 -1 -1 -1  6 -1 -1 -1  6  7  8  8  8 -1 -1 -1 -1  9 -1 10
 11 -1 12 -1 -1  6  6  6 -1 -1  1  4 -1 -1  6  6 10 -1 10 -1 13 13 13 -1
 -1 -1 -1 -1 14 14 14 -1 -1 -1 -1 -1 -1 -1 10 10 15 -1 -1 16 -1 17 -1 17
 18 18 18  9 -1 -1 -1  0  0 -1 -1 16 -1 -1 -1 -1 -1 -1 15 15 12 19 19 12
 -1 -1 -1 -1 20 20 20 12 -1 -1 -1  9  9 -1 11 -1 -1 21 -1 -1 -1 -1 -1 22
 22 22 -1 22 22 -1 21 -1  5 -1 23 23 -1]
cluster label cho esp 0.45: [-1 -1  0 -1  1  0 -1  1  2  0 -1  3  2 -1  0 -1  4  0  5  0  4  4  4 -1
 -1  1  6  0 -1 -1 -1 -1  0 -1 -1 -1  0  5  7  7  7 -1 -1 -1  5  8 -1  9
 10 -1 11 -1 -1  0  0  0 -1  0  1  3  0 -1  0  0  9 -1  9 -1  0  0  0  0
 -1 -1 -1 -1 12 12 12  9 -1 -1 -1 -1 -1 -1  9  9 13 -1 -1 14 14 15  6 15
 16 16 16  8 -1 -1 -1  0  0  0 17 14 -1 -1 -1 -1 -1  5 13 13 11 18 18 11
 -1 -1 -1 -1 17 17 17 11 -1 -1 -1  8  8 -1 10 -1 -1 19 -1 -1 20 20 -1 21
 21 21 -1 21 21 -1 19 -1  4 -1 22 22 -1]
cluster label cho esp 0.5: [-1 -1  0  1  1  0 -1  1  2  0 -1  3  2 -1  0 -1  4  0  5  0  4  4  4 -1
 -1  1  6  0 -1 -1 -1 -1  0  5 -1  2  0  5  7  7  7 -1 -1 -1  5  8 -1  9
 10 -1 11 -1 -1  0  0  0 -1  0  1  3  0 -1  0  0  9  9  9 -1  0  0  0  0
 -1 -1 -1 -1 12 12 12  9 -1 -1 -1 -1  0 -1  9  9 13 -1 -1 14 14 15  6 15
 16 16 16  8 -1 -1 -1  0  0  0 17 14 -1 -1 -1  0 -1  5 13 13 11  9  9 11
  0 -1 -1 -1 17 17 17 11 -1 -1 -1  8  8 -1 10 -1 -1 18 -1 -1 19 19 -1 20
 20 20  5 20 20 -1 18 -1  4 -1 21 21 -1]

# Detect New Log

In [50]:
new_logs = ["Detect a virus from IP 10.2.39.122", "Reject a virus from IP 10.2.21.122"]

for new_log in new_logs:
  result = miner.add_log_message(new_log)

  if result["change_type"] == "cluster_created":
      print("\n[CẢNH BÁO] ĐÃ PHÁT HIỆN TEMPLATE LOG MỚI XUẤT HIỆN!")
      print(f"ID cụm mới: {result['cluster_id']}")
      print(f"Nội dung Template: {result['template_mined']}")
      print(f"Log thô kích hoạt: {new_log}\n")

  elif result["change_type"] == "cluster_template_changed":
      print(f"[Cập nhật] Template ID {result['cluster_id']} thay đổi cấu trúc sang dạng: {result['template_mined']}")
  else:
      print("Không có sự thay đổi nào được phát hiện.")

Không có sự thay đổi nào được phát hiện.

[CẢNH BÁO] ĐÃ PHÁT HIỆN TEMPLATE LOG MỚI XUẤT HIỆN!
ID cụm mới: 161
Nội dung Template: Reject a virus from IP 10.2.21.122
Log thô kích hoạt: Reject a virus from IP 10.2.21.122